// usage: node scripts/gen-dome.mjs
// Draws MIT's Great Dome from primitives into app/lib/dome-pixels.ts.

import { writeFileSync, mkdirSync } from "node:fs";

const W = 104;
const H = 68;

const GROUND = 61;
const CX = 52;

function hash(x, y) {
  let h = x * 374761393 + y * 668265263;
  h = (h ^ (h >> 13)) * 1274126177;
  return ((h ^ (h >> 16)) >>> 0) / 4294967296;
}

const grid = Array.from({ length: H }, () => new Uint8Array(W));
const set = (x, y, v = 1) => {
  if (x >= 0 && x < W && y >= 0 && y < H) grid[y][x] = v;
};
const rect = (x0, y0, x1, y1) => {
  for (let y = y0; y < y1; y++) for (let x = x0; x < x1; x++) set(x, y);
};

rect(0, 46, 16, GROUND);
rect(W - 16, 46, W, GROUND);
for (let x = 2; x < 14; x += 3)
  for (let y = 49; y < 58; y += 4) {
    set(x, y, 0);
    set(x + 1, y, 0);
    set(x, y + 1, 0);
    set(x + 1, y + 1, 0);
  }
for (let x = W - 14; x < W - 2; x += 3)
  for (let y = 49; y < 58; y += 4) {
    set(x, y, 0);
    set(x + 1, y, 0);
    set(x, y + 1, 0);
    set(x + 1, y + 1, 0);
  }

rect(14, 40, W - 14, GROUND);

const colTop = 44;
const colBottom = 57;
for (let i = 0; i < 9; i++) {
  const gx = 20 + i * 7;
  for (let y = colTop; y < colBottom; y++) for (let x = gx; x < gx + 4; x++) set(x, y, 0);
}
rect(14, 40, W - 14, 44);
rect(14, 57, W - 14, GROUND);

rect(24, 33, W - 24, 40);
for (let x = 34; x < W - 34; x += 2) set(x, 36, 0);

rect(34, 27, W - 34, 33);
for (let x = 37; x < W - 37; x += 4) {
  set(x, 29, 0);
  set(x, 30, 0);
}

const domeR = 19;
const domeCY = 27;
for (let y = domeCY - domeR; y <= domeCY; y++)
  for (let x = CX - domeR; x <= CX + domeR; x++) {
    const dx = (x - CX) / domeR;
    const dy = (y - domeCY) / domeR;
    if (dx * dx + dy * dy <= 1) set(x, y);
  }
for (const a of [-0.72, -0.4, 0, 0.4, 0.72]) {
  for (let t = 0; t < domeR; t++) {
    const x = Math.round(CX + Math.sin(a) * t);
    const y = Math.round(domeCY - Math.cos(a) * t);
    if (t > 7 && t < domeR - 2) set(x, y, 0);
  }
}
rect(CX - 3, domeCY - domeR - 4, CX + 3, domeCY - domeR + 2);
rect(CX - 1, domeCY - domeR - 6, CX + 1, domeCY - domeR - 4);

rect(20, GROUND, W - 20, GROUND + 2);
rect(12, GROUND + 2, W - 12, GROUND + 4);

const src = grid.map((r) => Uint8Array.from(r));
const at = (x, y) => (x < 0 || x >= W || y < 0 || y >= H ? 0 : src[y][x]);
const near = (x, y, v) => {
  for (let dy = -2; dy <= 2; dy++)
    for (let dx = -2; dx <= 2; dx++) if (at(x + dx, y + dy) === v) return true;
  return false;
};

for (let y = 0; y < H; y++)
  for (let x = 0; x < W; x++) {
    const n = hash(x, y);
    if (at(x, y) === 1 && near(x, y, 0) && n > 0.62) grid[y][x] = 0;
    if (at(x, y) === 0 && near(x, y, 1) && n > 0.9) grid[y][x] = 1;
  }

const rows = grid.map((row) => {
  const runs = [];
  let x = 0;
  let cur = 0;
  let len = 0;
  for (; x < W; x++) {
    if (row[x] === cur) len++;
    else {
      runs.push(len);
      cur = row[x];
      len = 1;
    }
  }
  if (len) runs.push(len);
  return runs;
});

const filled = grid.reduce((n, r) => n + r.reduce((m, v) => m + v, 0), 0);

mkdirSync("app/lib", { recursive: true });
writeFileSync(
  "app/lib/dome-pixels.ts",
  `// GENERATED by scripts/gen-dome.mjs. Do not edit by hand.

export const DOME = {
  w: ${W},
  h: ${H},
  rows: [
${rows.map((r) => `    [${r.join(",")}],`).join("\n")}
  ] as number[][],
};
`,
);

console.log(`wrote app/lib/dome-pixels.ts — ${W}x${H}, ${filled} lit pixels`);

console.log(grid.map((r) => Array.from(r, (v) => (v ? "█" : "·")).join("")).join("\n"));
