// usage: node scripts/gen-sprites.mjs [path/to/sprites.h]
// Decodes the PSoC firmware's RGB565 sprite tables into app/lib/psoc-sprites.ts.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { deflateSync } from "node:zlib";
import { homedir } from "node:os";
import path from "node:path";

const SRC =
  process.argv[2] ??
  path.join(homedir(), "Downloads/Academics/6.115/Design01.cydsn/sprites.h");

const DIMS = { SPR: [16, 16], HUD: [13, 23], FACE: [24, 24] };

const TRANSPARENT_BLACK = new Set(["SPR_CURSOR"]);

const crcTable = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(buf) {
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = crcTable[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}

function encodePng(w, h, rgba) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(w, 0);
  ihdr.writeUInt32BE(h, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // RGBA
  const raw = Buffer.alloc(h * (w * 4 + 1));
  for (let y = 0; y < h; y++) {
    raw[y * (w * 4 + 1)] = 0; // filter: none
    rgba.copy(raw, y * (w * 4 + 1) + 1, y * w * 4, (y + 1) * w * 4);
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", ihdr),
    chunk("IDAT", deflateSync(raw, { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

const src = readFileSync(SRC, "utf8");
const re = /static\s+const\s+uint16\s+(\w+)\s*\[\s*(\d+)\s*\]\s*=\s*\{([\s\S]*?)\};/g;

const out = {};
let m;
while ((m = re.exec(src))) {
  const [, name, count, body] = m;
  const values = body
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)
    .map((s) => parseInt(s.replace(/u$/i, ""), 16));

  if (values.length !== Number(count)) {
    console.warn(`  ! ${name}: parsed ${values.length}, declared ${count} — skipped`);
    continue;
  }

  const prefix = name.split("_")[0];
  const dims = DIMS[prefix];
  if (!dims) {
    console.warn(`  ! ${name}: no dimensions for prefix ${prefix} — skipped`);
    continue;
  }
  const [w, h] = dims;
  if (w * h !== values.length) {
    console.warn(`  ! ${name}: ${values.length} px does not fit ${w}x${h} — skipped`);
    continue;
  }

  const keyTransparent = TRANSPARENT_BLACK.has(name);
  const rgba = Buffer.alloc(w * h * 4);
  values.forEach((v, i) => {
    const r5 = (v >> 11) & 0x1f;
    const g6 = (v >> 5) & 0x3f;
    const b5 = v & 0x1f;
    rgba[i * 4] = Math.round((r5 * 255) / 31);
    rgba[i * 4 + 1] = Math.round((g6 * 255) / 63);
    rgba[i * 4 + 2] = Math.round((b5 * 255) / 31);
    rgba[i * 4 + 3] = keyTransparent && v === 0 ? 0 : 255;
  });

  out[name] = {
    w,
    h,
    uri: `data:image/png;base64,${encodePng(w, h, rgba).toString("base64")}`,
  };
}

const names = Object.keys(out).sort();
const body = names
  .map((n) => `  ${n}: { w: ${out[n].w}, h: ${out[n].h}, uri: "${out[n].uri}" },`)
  .join("\n");

mkdirSync("app/lib", { recursive: true });
writeFileSync(
  "app/lib/psoc-sprites.ts",
  `// GENERATED by scripts/gen-sprites.mjs from the PSoC firmware's sprites.h.

export type Sprite = { w: number; h: number; uri: string };

export const SPRITES = {
${body}
} satisfies Record<string, Sprite>;

export type SpriteName = keyof typeof SPRITES;
`,
);

const bytes = names.reduce((n, k) => n + out[k].uri.length, 0);
console.log(`wrote app/lib/psoc-sprites.ts — ${names.length} sprites, ${(bytes / 1024).toFixed(1)} KB`);
console.log(names.join(", "));
